name: style

on:
  push:
    branches: [ master, dev** ]
  pull_request:
    branches: [ master ]

jobs:
  style:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Check code style
      run: ./utils/format -n
